pipeline {
    environment {
        registry = 'bullhorn/ils2'
        DOCKERHUB_CREDENTIALS = credentials('jenkins-dockerhub')
        DOCKER_IMAGE_NAME = "bullhorn/ils2"
        DOCKER_IMAGE_TAG = "dev"
    }
    agent {
            label 'Dockerhost'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }
    stages {
        stage('Checkout Main branch') {
            steps {
                git branch: 'main',
                git credentialsId: 'jenkins-github-demo',
                url: 'git@github.com:bullmoon/ILS-web-2.0.git'
                #deleteDir()
                #checkout scm
            }
        }
        stage('Publish Docker image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'jenkins-dockerhub') {
                        dockerImage.push()
                    }
                }
            }
        }

    }
}